### PR TITLE
Slides for Go with Visual Studio Code

### PR DESCRIPTION
**Pull request by ramya-rao-a**

### CODE REVIEW

**Comment by losinggeneration** [comment]
Was this a lightning talk? I don't recall seeing this as part of the tutorial sections. If so, there's a directory for lightning talks that this should probably be moved to.

**Comment by ramya-rao-a** [comment]
Yes, this was a lightning talk.
I have moved the pdf to the right folder npw

**Comment by ramya-rao-a** [comment]
cc @bketelsen

**Comment by bketelsen** [comment]
thanks!

**Pull request merged**
